/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BongoCat(props) {
  const { nodes, materials } = useGLTF('/bongo_cat.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.04, 0, 0]} scale={[4.02/2, 2.58/2, 2.19/2]}>
        <mesh receiveShadow castShadow geometry={nodes.Sphere_1.geometry} material={materials['Material.001']} />
        <mesh receiveShadow castShadow geometry={nodes.Sphere_2.geometry} material={materials['Material.004']} />
        <mesh receiveShadow castShadow geometry={nodes.Sphere_3.geometry} material={materials['Material.006']} />
        <mesh receiveShadow castShadow geometry={nodes.Sphere_4.geometry} material={materials['Material.002']} />
      </group>
      <mesh receiveShadow geometry={nodes.Cube.geometry} scale={[0.5,0.8,0.5]} material={materials['Material.003']} position={[0, -0.4, 1.7]} />
    </group>
  )
}

useGLTF.preload('/bongo_cat.gltf')
